version: '3.9'
services:
  fast-database:
    container_name: fast-database
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=fastservice
    networks:
      - local

networks:
  local:
    name: fastservice

